language: python
python:
  - 3.7
os: linux
services:
  - docker
install:
  # - pipenv install --dev
  - pip install m2r
script:
  - pip install -e .
  - python -m postgresimporter.tests.run_tests
  # - pipenv run pytest
  # Ignore errors when compiling
  # - docker run --entrypoint pip python:latest install postgresimporter || true
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: GqQCdKP0i6IZabJMHd7uAfuZplN+/09QnC00ARirunmdNdJYxIEN6KoeiGjTzZ7D9y5NtlzqJ+ODD3K6UTTWvM2p12bwsOjncFDIJFJjaQqvETCkfhluZSEhjEytcU5KxGv2djlj6EZZ8AY0sEuY9hZFEZ3bISAubhDQ34rBjBoMwTfefQRH/Fec3ngmw7R04FPw+WmpO4JSO0+rcdEgajA8L12kmTNUTZFMTJVfDaIqGZZlmwW4bNbakCpLeOezJ0XU8Tg2dU/BiwIvC4DtzzX3nMgElP3cN300gs95wEl9Vbcx0q7nIcSahnrfzJjNOa3CfhyHW9Dcbh4ecabtfwNN9h6w6NLmyrsAOMDC2GO7edPBBHcsBTC6R14v+kGy9VTe0XCTMReGxhp2ASA21BQD/7hpbtG0133wFf9M6uwlVzlMVoi5OZFjrqPZz9Gy5RMdTi18HbFAo/r9kPg+hFprVH4mu0l5wkxmzKSO/mbas1BeuX9aC8NPmpViRlZUXGhZR9RCukadi+lycjrqZNwXBtam3EZPLiSat4KAV67lHucqcx3FqFjbpt9XWEbuEusUcJWZgLmiAvXdipIgoJ2iuIEQoc9xizRT3lbmvbtDa/sBTRUca/Qo++iuMdu1Mezi6WnqZkJUsDA650N0PHOUxkST04EyyOiWKSJntvQ=
